@startuml

title __ENGINE's Class Diagram__\n

  package engine {
    package engine.collision {
      package engine.collision.aabb {
        class AABBAABBCollision {
        }
      }
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.aabb {
        abstract class AABBCollision {
        }
      }
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.aabb {
        class AABBOBBCollision {
        }
      }
    }
  }
  

  package world {
    package world.bounding {
      class AABBProperties {
      }
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.aabb {
        class AABBSphereCollision {
        }
      }
    }
  }
  

  package object {
    class Ball {
    }
  }
  

  package world {
    package world.bounding {
      class Bounding {
      }
    }
  }
  

  package world {
    package world.bounding {
      abstract class BoundingProperties {
      }
    }
  }
  

  package world {
    package world.bounding {
      class BoundingSphereProperties {
      }
    }
  }
  

  package engine {
    package engine.collision {
      abstract class Collision {
      }
    }
  }
  

  package engine {
    package engine.collision {
      class CollisionFactory {
      }
    }
  }
  

  package engine {
    package engine.collision {
      class CollisionFactoryException {
      }
    }
  }
  

  package engine {
    package engine.collision {
      class CollisionHandler {
      }
    }
  }
  

  package engine {
    class Config {
    }
  }
  

  package engine {
    class Engine {
    }
  }
  

  package engine {
    abstract class EngineObject {
    }
  }
  

  package engine {
    class Maze {
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.obb {
        class OBBAABBCollision {
        }
      }
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.obb {
        abstract class OBBCollision {
        }
      }
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.obb {
        class OBBOBBCollision {
        }
      }
    }
  }
  

  package world {
    package world.bounding {
      class OBBProperties {
      }
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.obb {
        class OBBSphereCollision {
        }
      }
    }
  }
  

  package world {
    class ONB3D {
    }
  }
  

  package world {
    class ONBException {
    }
  }
  

  package engine {
    class ObjectContainer {
    }
  }
  

  package world {
    class Octree {
    }
  }
  

  package engine {
    package engine.particle {
      class Particle {
      }
    }
  }
  

  package engine {
    package engine.particle {
      package engine.particle.link {
        class ParticleCable {
        }
      }
    }
  }
  

  package engine {
    package engine.collision {
      class ParticleCollision {
      }
    }
  }
  

  package engine {
    package engine.particle {
      interface ParticleCollisionGenerator {
      }
    }
  }
  

  package engine {
    package engine.particle {
      class ParticleDrag {
      }
    }
  }
  

  package engine {
    package engine.particle {
      interface ParticleForceGenerator {
      }
    }
  }
  

  package engine {
    package engine.particle {
      class ParticleForceRegistry {
      }
    }
  }
  

  package engine {
    package engine.particle {
      class ParticleGravity {
      }
    }
  }
  

  package engine {
    package engine.particle {
      package engine.particle.link {
        abstract class ParticleLink {
        }
      }
    }
  }
  

  package engine {
    package engine.particle {
      package engine.particle.link {
        class ParticleRod {
        }
      }
    }
  }
  

  package engine {
    package engine.particle {
      class ParticleWorld {
      }
    }
  }
  

  package object {
    class Pawn {
    }
  }
  

  package engine {
    abstract class PhysicalObject {
    }
  }
  

  package engine {
    class Physics {
    }
  }
  

  package engine {
    abstract class PlayableObject {
    }
  }
  

  package engine {
    class Player {
    }
  }
  

  package world {
    class Point3D {
    }
  }
  

  package world {
    class Polygon {
    }
  }
  

  package world {
    class PolygonException {
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.sphere {
        class SphereAABBCollision {
        }
      }
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.sphere {
        abstract class SphereCollision {
        }
      }
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.sphere {
        class SphereOBBCollision {
        }
      }
    }
  }
  

  package engine {
    package engine.collision {
      package engine.collision.sphere {
        class SphereSphereCollision {
        }
      }
    }
  }
  

  package object {
    class Tile {
    }
  }
  

  package world {
    class Vector3D {
    }
  }
  

  package object {
    class Wall {
    }
  }
  

  AABBAABBCollision -up-|> AABBCollision
  AABBCollision -up-|> Collision
  AABBOBBCollision -up-|> AABBCollision
  AABBProperties -up-|> BoundingProperties
  AABBSphereCollision -up-|> AABBCollision
  Ball -up-|> PhysicalObject
  Bounding o-- Point3D : anchor
  Bounding o-- BoundingProperties : properties
  BoundingSphereProperties -up-|> BoundingProperties
  Collision o-- PhysicalObject : thisNode
  Collision o-- EngineObject : otherNode
  Collision o-- Vector3D : normal
  Engine -up-|> JFrame
  EngineObject o-- Point3D : anchor
  EngineObject o-- Bounding : bounding
  EngineObject o-- Bounding : broadPhase
  OBBAABBCollision -up-|> OBBCollision
  OBBCollision -up-|> Collision
  OBBOBBCollision -up-|> OBBCollision
  OBBProperties -up-|> BoundingProperties
  OBBProperties o-- ONB3D : onb
  OBBSphereCollision -up-|> OBBCollision
  ONB3D o-- Vector3D : x
  ONB3D o-- Vector3D : y
  ObjectContainer -up-|> Iterable
  ObjectContainer -up-|> Observable
  ObjectContainer o-- Octree : octree
  Octree o-- Octree : parent
  Octree o-- Point3D : root
  Octree o-- Bounding : bounding
  Particle o-- Point3D : position
  Particle o-- Vector3D : velocity
  Particle o-- Vector3D : acceleration
  Particle o-- Vector3D : total_force
  ParticleCable -up-|> ParticleLink
  ParticleCollision o-- Particle : p1
  ParticleCollision o-- Particle : p2
  ParticleCollision o-- Vector3D : normal
  ParticleDrag -up-|> ParticleForceGenerator
  ParticleGravity -up-|> ParticleForceGenerator
  ParticleGravity o-- Vector3D : gravity
  ParticleLink o-- Particle : p1
  ParticleLink o-- Particle : p2
  ParticleRod -up-|> ParticleLink
  ParticleWorld o-- ParticleForceRegistry : pfr
  ParticleWorld o-- CollisionHandler : ch
  Pawn -up-|> PlayableObject
  PhysicalObject -up-|> EngineObject
  PhysicalObject o-- Vector3D : velocity
  PhysicalObject o-- Vector3D : acceleration
  PhysicalObject o-- Vector3D : nextMovement
  PhysicalObject o-- Bounding : nextBounding
  PlayableObject -up-|> PhysicalObject
  PlayableObject o-- Player : player
  Player -up-|> KeyListener
  Player -up-|> MouseMotionListener
  Player o-- PlayableObject : playerObject
  Polygon o-- Vector3D : normal
  SphereAABBCollision -up-|> SphereCollision
  SphereCollision -up-|> Collision
  SphereOBBCollision -up-|> SphereCollision
  SphereSphereCollision -up-|> SphereCollision
  Tile -up-|> EngineObject
  Tile o-- Polygon : main
  Tile o-- Polygon : padding
  Wall -up-|> EngineObject
  Wall o-- Polygon : main
  Wall o-- Polygon : padding1
  Wall o-- Polygon : padding2


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
